### PR TITLE
V/1.21.30 & Small fixes

### PR DESCRIPTION
**Pull request by Superomarking**
- PR name: Added 1.21.30 & Fixed a few issues

- PR description: Adds the 1.21.30 version alongside bug fixes

- Changes: Added relative packets/translations for 1.21.30
- Relevant issues: 

- Affected Versions: 1.21.30

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Superomarking** [comment]
If anyone could test this out it would be very helpful

**Comment by Beavermon** [comment]
Sure

**Comment by Superomarking** [comment]
BEAVER GO BACK TO BUILDING ZEQA MAPS

**Comment by Beavermon** [comment]
jn0no

**Pull request merged**
